# Site settings
title: All Things DevOps
description: Collection of notes, projects, and documentations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joseeden.github.io" 

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

gem "github-pages", group: :jekyll_plugins